### ISSUE TITLE
[v0.9.9] testing of build 0.9.9.v20180121-1054

### ISSUE THREAD

**Issue by anb0s** [anb0s/LogViewer#90]
I need help with testing of the build
tag: **v0.9.9.beta1**
commit: **486800525da24a082f2c0fb3ba1fe2014f7ff365**

It is available at the testing update site now: http://anb0s.github.io/LogViewer/testing
version: **LogViewer 0.9.9.v20180121-1054**

**Use "Help | Install New Software...", paste the link and select the right version!**

new found and open issues or enhancement requests that will be addressed in next test build:

new fixed issues in this build:
- [x] #61 Logviewer does not remove it's preference store PropertyChangeListener
- [x] #65 Unable to Open Console in LogViewer
- [x] #76 Failed to open Log Viewer from console: unable to load resource ProcessConsole\JettyApp [Java Application] ...
- [x] #80 Server returned lastModified <= 0
- [x] #83 Eclipse Mars: cannot locate the resource
- [x] #85 migration to GitHub

fixed issues with previous build(s):
...

**Comment by anb0s** [comment]
next build #92
