### ISSUE TITLE
[v0.9.9] testing of build 0.9.9.v20180129-1416

### ISSUE THREAD

**Issue by anb0s** [anb0s/LogViewer#92]
I need help with testing of the build
tag: **v0.9.9.beta2**
commit: ****

It is available at the testing update site now: http://anb0s.github.io/LogViewer/testing
version: **LogViewer 0.9.9.v20180129-1416**

**Use "Help | Install New Software...", paste the link and select the right version!**

new found and open issues or enhancement requests that will be addressed in next test build:

new fixed issues in this build:
- [x] #34 Truncate logs
- [x] #46 An idea for Logviewer(Clear logviewer Console)
- [x] #88 "Clean log" button

fixed issues with previous build(s):
  - [x] #90 [v0.9.9] testing of build 0.9.9.v20180121-1054
  - [x] #61 Logviewer does not remove it's preference store PropertyChangeListener
  - [x] #65 Unable to Open Console in LogViewer
  - [x] #76 Failed to open Log Viewer from console: unable to load resource ProcessConsole\JettyApp [Java Application] ...
  - [x] #80 Server returned lastModified <= 0
  - [x] #83 Eclipse Mars: cannot locate the resource
  - [x] #85 migration to GitHub

**Comment by ramonamorea** [comment]
Hi, I downloaded the build yesterday and everything is fine. 
I tested the issues you mentioned and also the added features and everything works fine!

Thanks for this addition!
Especially the Clear Log button is extremely helpful.

I'm using Eclipse for PHP Developers
Version: Neon.3 Release (4.6.3)

**Comment by anb0s** [comment]
Thanks for helping with testing!

**Comment by anb0s** [comment]
next testing build #96
